### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by AnshikaG0219** [AnshikaG0219/Timeless#1]
Show your creativity and skills by adding animation in home page.
Or you can create a new home page altogether.

**Comment by noaYarin** [comment]
Please assign it to me.

**Comment by AnshikaG0219** [comment]
You're free to work on the issue, while creating a PR though please make sure to add screenshots of your work.
Happy Coding :)

**Comment by AnshikaG0219** [comment]
> You're free to work on the issue, while creating a PR though please make sure to add screenshots of your work. Happy Coding :)



> Please assign it to me.

You're free to work on the issue, while creating a PR though please make sure to add screenshots of your work.
Happy Coding :)

**Comment by AnshikaG0219** [comment]
> Please assign it to me.

You're free to work on the issue, while creating a PR though please make sure to add screenshots of your work.
Happy Coding :)

**Comment by YarinLevi5** [comment]
Ok  , where am I supposed to put those screenshots?

**Comment by noaYarin** [comment]
TNX!
