### ISSUE TITLE
Log in Page

### ISSUE THREAD

**Issue by AnshikaG0219** [AnshikaG0219/Timeless#3]
Make a log in page which takes name, email and password. All the fields as required.

**Comment by MedhaRagh** [comment]
[login.txt](https://github.com/AnshikaG0219/Timeless/files/6758075/login.txt)

**Comment by MedhaRagh** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <style>
        body
        {
            background-color:cornflowerblue;
            text-align:center;
            
           
            
        }
        .login-div
        {
            background-color: white;
            margin:100px auto;
            width: 350px;
            padding: 60px;
           
        }
        .title
        {
            text-align: center;
            color: #505050;
            font-size:30px;
            font-weight:bolder;
        }
        .form
        {
            width: 100%;
            margin-top:30px;
            
        }
        .form input{
            font-size: 17px;
            padding: 10px 20px 10px 5px;
            border: none;
            background: none;
            outline: none;
        }
        .username, .password, .email
        {
            display: block;
            border-radius: 31px;
            padding: 10px;
            margin: 10px 0;
            border:1px solid rgba(0,0,0,0.2);
        }
        .options
        {
            display: flex;
            flex-direction: row;
            justify-content:space-between;
            padding: 5px 0;
        }

        button.signin-btn
        {
            width:100%;
            padding:12px 10px;
            border: none;
            font-size: 18px;
            border-radius: 29px;
            background-color: red;
        }
        .sign-up
        {
            text-align:center;
        }
        
        
        </style>
</head>
<body>
    <div class = "login-div">
        <div class = "logo">
          <img src = "E:\Desktop\woman.png">
        </div>
        <div class = "title">Login Page</div>
        <div class = "form">
          <div class = "username">
            <input type = "text" placeholder = "Username">
          </div>
          <div class = "email">
            <input type = "text" placeholder = "Email ID">
          </div>
          <div class = "password">
            <input type = "password" placeholder = "Password">
  
          </div>
  
          <div class = "options">
            <div class = "remember-me">
              <input type = "checkbox">
              <label for = "remember-me">Remember me</label>
            </div>
            <div class = "forgot-password">
              <a href = "#">Forgot Password</a>
            </div>
          </div>
          <button class = "signin-btn">Login</button>
  
          <div class="sign-up">
            <a href = "#">New here? Sign Up Now</a>
          </div>
        </div>
      </div>
    </body>
</body>
</html>`

**Comment by MedhaRagh** [comment]
[login.txt](https://github.com/AnshikaG0219/Timeless/files/6758082/login.txt)

**Comment by AnshikaG0219** [comment]
This is good but I think you can do more styling.

**Comment by MedhaRagh** [comment]
Thank you! I'll improve it.

**Comment by Gauravkumar2701** [comment]
Hi I want to work on this issue can you assign this to me.

**Comment by mscpereira** [comment]
Hello @AnshikaG0219 . I know this is not the correct place but I'm trying to do my first contribution with a login form, but when I try to pull req it says I don't have access. Can you help me pls? thanks

**Comment by AnshikaG0219** [comment]
@mscpereira Hey, what branch are you working on?
"Pull requests can only be opened between two branches that are different."

**Comment by mscpereira** [comment]
Hey. Thanks for reply. I'm new to this and I followed the documentation but
it's not working. I forked, cloned and created a branch with git checkout -
b branch_name but when I try to pull and put the password it says I don't
have access to the project..?

A seg, 8 de nov de 2021, 12:44, Anshika Gautam ***@***.***>
escreveu:

**Comment by AnshikaG0219** [comment]
While creating the pull request you have to compare two different branches, You must have pushed your code your new branch so just **select the required branch** from the dropdown and you will be good to go.
**Also make sure you have correct repos opened**

![image](https://user-images.githubusercontent.com/41854014/140787563-67fc4e01-7ec1-4675-9139-db1cfec39198.png)

**Comment by mscpereira** [comment]
Ok, I finally did it but only worked with the desktop app. Thanks for your
help. If I did anything wrong just let me know since it's my first
submission :)
Thank you.

**Comment by AnshikaG0219** [comment]
@mscpereira Hey it would be better if you could send a video or screenshot of your work.
